services:
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "6064:8080"
    environment:
      ADMINER_DEFAULT_SERVER: "host.docker.internal"
    extra_hosts:
      - "host.docker.internal:host-gateway"
